# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180419_0439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='choicetext',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='questiontext',
        ),
    ]
